[tool.pytest.ini_options]
addopts = ["-rfEX", "-pno:warnings", "-vv"]
python_files = ["test_*.py", "*_test.py"]
testpaths = ["tests"]

[tool.black]
line-length = 88
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.tox
    | \.venv
    | _build
    | .build
    | bazel-*
    | build
    | venv
    | lib
    | dist
    | typings
  )/
)
'''

[tool.ruff]
# similar to black's
line-length = 88
# We ignore E501 (line too long) here because we keep user-visible strings on one line.
ignore = ["E501"]
exclude = ["bazel-*/", "venv", "typings"]
target-version = "py311"

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.isort]
lines-after-imports = 2

[tool.isort]
profile = "black"
line_length = 88
length_sort = true
force_single_line = true
order_by_type = true
known_first_party = ["bentoml"]
force_alphabetical_sort_within_sections = true
skip_glob = ["typings/*", "tests/*", "venv/*", "lib/*", "bazel-*"]

[tool.pyright]
pythonVersion = "3.11"
exclude = ["bazel-*"]
analysis.useLibraryCodeForTypes = true
strict = true
strictListInference = true
strictDictionaryInference = true
strictSetInference = true
strictParameterNoneValue = true
enableTypeIgnoreComments = true
